# Generated by Django 3.0.4 on 2020-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
